project_id = "dcjhxvoyheyjgocohihp"

[functions.shopify-billing]
verify_jwt = false

[functions.shopify-oauth]
verify_jwt = false

[functions.shopify-webhooks]
verify_jwt = false

[functions.track-click]
verify_jwt = false
